export type RootDrawerParamList = {
    Connected: undefined;
    Home: undefined;
    NoRegistered: {data: any};
    RegisterUser: {data: any};
    Registered: {data: any};
    RegisterPassword: {data: any};
    PasswordChanged: {data: any};
    PasswordAltered: {data: any};
    Account: undefined;
    Crediary: undefined;
    SignIn: undefined;
    CheckPassword: {data: any};
    LoadImages: {user: any};
    AlterPassword: {user: any};
    PrivacyPolice: undefined;
    PrivacySettings: undefined;
    StoreList: {data: any};
    StoreSelected: {data: any};
    StoresLocation: {data: any};
    Contact: undefined;
    History: undefined;
    HistoryItem: {data: any};
    ImagesSent: undefined;
    Protocol: undefined;
    Detail: {data: any};
    Questions: undefined;
    Methods: {order: any};
    OpenPayments: undefined;
    HistoryPayments: undefined;
    PixPayment: {order: any};
    SlipPayment: {order: any};
    CartPayment: {order: any};
    Twobillet: undefined;
    ActionBillet: {order: any};
    PayCartOk: undefined;
};
